import { PantryConfirmationStatus, PantryConversionStatus, PantryItemSource } from '@prisma/client';

export interface SeedPantryItem {
  id: string;
  ingredientNormalizedName: string;
  quantity: number;
  unit: string;
  normalizedGrams: number;
  conversionStatus: PantryConversionStatus;
  conversionSource: string;
  conversionVersion: string;
  conversionConfidence: number;
  source: PantryItemSource;
  confirmationStatus: PantryConfirmationStatus;
  freshnessNote: string;
  expiresInDays: number;
  idempotencyKey: string;
}

export const pantryDefinitions: readonly SeedPantryItem[] = [
  {
    id: '20000000-0000-4000-8000-000000000001',
    ingredientNormalizedName: 'dau hu',
    quantity: 2,
    unit: 'bìa',
    normalizedGrams: 300,
    conversionStatus: PantryConversionStatus.CONVERTED,
    conversionSource: 'PROJECT_CURATED',
    conversionVersion: '1.0',
    conversionConfidence: 0.95,
    source: PantryItemSource.MANUAL,
    confirmationStatus: PantryConfirmationStatus.CONFIRMED,
    freshnessNote: 'Đậu hũ non ép ráo để ngăn mát tủ lạnh, nên dùng trong vòng 2 ngày.',
    expiresInDays: 2, // Gần hết hạn để kiểm thử cảnh báo Expiry Alert
    idempotencyKey: 'seed-pantry-tofu-01',
  },
  {
    id: '20000000-0000-4000-8000-000000000002',
    ingredientNormalizedName: 'nam bao ngu',
    quantity: 200,
    unit: 'g',
    normalizedGrams: 200,
    conversionStatus: PantryConversionStatus.CONVERTED,
    conversionSource: 'SYSTEM_MASS',
    conversionVersion: 'UCUM-MASS-V1',
    conversionConfidence: 1.0,
    source: PantryItemSource.MANUAL,
    confirmationStatus: PantryConfirmationStatus.CONFIRMED,
    freshnessNote: 'Nấm tươi mua sáng nay tại chợ rau hữu cơ, tai dày và khô ráo.',
    expiresInDays: 3,
    idempotencyKey: 'seed-pantry-mushroom-02',
  },
  {
    id: '20000000-0000-4000-8000-000000000003',
    ingredientNormalizedName: 'bong cai xanh',
    quantity: 1,
    unit: 'cây',
    normalizedGrams: 350,
    conversionStatus: PantryConversionStatus.CONVERTED,
    conversionSource: 'PROJECT_CURATED',
    conversionVersion: '1.0',
    conversionConfidence: 0.9,
    source: PantryItemSource.MANUAL,
    confirmationStatus: PantryConfirmationStatus.CONFIRMED,
    freshnessNote: 'Bông cải bọc màng thực phẩm để ngăn mát.',
    expiresInDays: 4,
    idempotencyKey: 'seed-pantry-broccoli-03',
  },
  {
    id: '20000000-0000-4000-8000-000000000004',
    ingredientNormalizedName: 'ca rot',
    quantity: 3,
    unit: 'củ',
    normalizedGrams: 360,
    conversionStatus: PantryConversionStatus.CONVERTED,
    conversionSource: 'PROJECT_CURATED',
    conversionVersion: '1.0',
    conversionConfidence: 0.9,
    source: PantryItemSource.MANUAL,
    confirmationStatus: PantryConfirmationStatus.CONFIRMED,
    freshnessNote: 'Cà rốt Đà Lạt còn cuống lá tươi.',
    expiresInDays: 7,
    idempotencyKey: 'seed-pantry-carrot-04',
  },
  {
    id: '20000000-0000-4000-8000-000000000005',
    ingredientNormalizedName: 'gao lut',
    quantity: 2000,
    unit: 'g',
    normalizedGrams: 2000,
    conversionStatus: PantryConversionStatus.CONVERTED,
    conversionSource: 'SYSTEM_MASS',
    conversionVersion: 'UCUM-MASS-V1',
    conversionConfidence: 1.0,
    source: PantryItemSource.MANUAL,
    confirmationStatus: PantryConfirmationStatus.CONFIRMED,
    freshnessNote: 'Túi gạo lứt hút chân không trong tủ khô.',
    expiresInDays: 120,
    idempotencyKey: 'seed-pantry-brown-rice-05',
  },
  {
    id: '20000000-0000-4000-8000-000000000006',
    ingredientNormalizedName: 'yen mach',
    quantity: 500,
    unit: 'g',
    normalizedGrams: 500,
    conversionStatus: PantryConversionStatus.CONVERTED,
    conversionSource: 'SYSTEM_MASS',
    conversionVersion: 'UCUM-MASS-V1',
    conversionConfidence: 1.0,
    source: PantryItemSource.MANUAL,
    confirmationStatus: PantryConfirmationStatus.CONFIRMED,
    freshnessNote: 'Yến mạch quaker cán dẹt bảo quản trong hũ kín chống ẩm.',
    expiresInDays: 90,
    idempotencyKey: 'seed-pantry-oats-06',
  },
  {
    id: '20000000-0000-4000-8000-000000000007',
    ingredientNormalizedName: 'hat chia',
    quantity: 250,
    unit: 'g',
    normalizedGrams: 250,
    conversionStatus: PantryConversionStatus.CONVERTED,
    conversionSource: 'SYSTEM_MASS',
    conversionVersion: 'UCUM-MASS-V1',
    conversionConfidence: 1.0,
    source: PantryItemSource.MANUAL,
    confirmationStatus: PantryConfirmationStatus.CONFIRMED,
    freshnessNote: 'Hạt chia hữu cơ nhập khẩu, đã mở nắp để nơi thoáng mát.',
    expiresInDays: 180,
    idempotencyKey: 'seed-pantry-chia-07',
  },
  {
    id: '20000000-0000-4000-8000-000000000008',
    ingredientNormalizedName: 'hat dieu',
    quantity: 300,
    unit: 'g',
    normalizedGrams: 300,
    conversionStatus: PantryConversionStatus.CONVERTED,
    conversionSource: 'SYSTEM_MASS',
    conversionVersion: 'UCUM-MASS-V1',
    conversionConfidence: 1.0,
    source: PantryItemSource.MANUAL,
    confirmationStatus: PantryConfirmationStatus.CONFIRMED,
    freshnessNote: 'Hạt điều rang mộc Bình Phước.',
    expiresInDays: 60,
    idempotencyKey: 'seed-pantry-cashew-08',
  },
  {
    id: '20000000-0000-4000-8000-000000000009',
    ingredientNormalizedName: 'men dinh duong',
    quantity: 150,
    unit: 'g',
    normalizedGrams: 150,
    conversionStatus: PantryConversionStatus.CONVERTED,
    conversionSource: 'SYSTEM_MASS',
    conversionVersion: 'UCUM-MASS-V1',
    conversionConfidence: 1.0,
    source: PantryItemSource.MANUAL,
    confirmationStatus: PantryConfirmationStatus.CONFIRMED,
    freshnessNote: 'Lọ men dinh dưỡng bổ sung vitamin B12.',
    expiresInDays: 200,
    idempotencyKey: 'seed-pantry-nooch-09',
  },
] as const;
