import type { RecipeDetailDto } from '../types/recipe.dto';

/**
 * Dữ liệu mẫu theo đúng shape backend `postSchema` (author/revision/categories/
 * media/recipe) để UI demo khi endpoint `/posts` còn PLANNED. Khi backend READY,
 * API client thay fixture bằng dữ liệu live mà không đổi mapper.
 */
export const MOCK_RECIPE_DTOS: RecipeDetailDto[] = [
  {
    id: 'rec-001',
    type: 'RECIPE',
    slug: 'dau-hu-sot-ca-chua-nam-huong',
    status: 'PUBLISHED',
    version: 1,
    publishedAt: '2026-09-10T08:30:00Z',
    createdAt: '2026-09-10T08:00:00Z',
    updatedAt: '2026-09-10T08:30:00Z',
    author: {
      id: 'usr-contributor-1',
      displayName: 'Bếp Chay An Nhiên',
      avatarUrl:
        'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    },
    revision: {
      id: 'rev-001',
      version: 1,
      status: 'PUBLISHED',
      title: 'Đậu hũ sốt cà chua nấm hương',
      excerpt: 'Món chay thanh đạm giàu đạm, sốt cà chua nấm hương đậm đà cho bữa cơm gia đình.',
      body: '## Bước 1\nÁp chảo đậu hũ trên chảo chống dính với ít dầu mè cho vàng đều các mặt rồi vớt ra đĩa có lót giấy thấm dầu.\n\n## Bước 2\nPhi thơm hành bo-rô, cho cà chua và nấm hương vào xào mềm, thêm 2 muỗng nước tương, 1 muỗng hạt nêm nấm và 50ml nước lọc nấu sôi sệt.\n\n## Bước 3\nCho đậu hũ vào đảo nhẹ tay cho thấm sốt trong 3 phút, rắc tiêu thơm và ngò rí lên trên trước khi tắt bếp.',
      tags: ['dau-hu', 'mon-xao', 'giau-dam'],
      createdAt: '2026-09-10T08:00:00Z',
    },
    categories: [
      { id: 'cat-recipe-1', name: 'Món xào chay', slug: 'mon-xao-chay', type: 'RECIPE_GROUP' },
    ],
    media: [
      {
        id: 'med-001',
        kind: 'COVER_IMAGE',
        provider: 'CLOUDINARY',
        secureUrl:
          'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=800&auto=format&fit=crop&q=80',
        mimeType: 'image/jpeg',
        bytes: 120000,
      },
    ],
    recipe: {
      servings: 4,
      prepTimeMinutes: 15,
      cookTimeMinutes: 20,
      difficulty: 'EASY',
      nutrition: {
        calories: 285,
        proteinGrams: 18.5,
        carbsGrams: 12.0,
        fatGrams: 16.2,
        fiberGrams: 4.5,
        vitaminB12Mcg: 0.0,
      },
      mealPlannerEligible: true,
      allergenCodes: ['SOY'],
      traditionWarnings: [],
      dietCompatibilities: [],
      ingredients: [
        {
          id: 'ri-001',
          ingredientId: 'ing-tofu-1',
          canonicalName: 'Đậu hũ',
          position: 0,
          displayName: 'Đậu hũ non hữu cơ',
          normalizedName: 'dau hu non huu co',
          amount: 3,
          unit: 'miếng',
          optional: false,
          resolutionStatus: 'EXACT',
        },
        {
          id: 'ri-002',
          ingredientId: 'ing-tomato-1',
          canonicalName: 'Cà chua',
          position: 1,
          displayName: 'Cà chua chín mọng',
          normalizedName: 'ca chua chin mong',
          amount: 3,
          unit: 'quả',
          optional: false,
          resolutionStatus: 'EXACT',
        },
        {
          id: 'ri-003',
          ingredientId: 'ing-mushroom-1',
          canonicalName: 'Nấm hương',
          position: 2,
          displayName: 'Nấm hương tươi',
          normalizedName: 'nam huong tuoi',
          amount: 100,
          unit: 'gram',
          optional: false,
          resolutionStatus: 'EXACT',
        },
        {
          id: 'ri-004',
          ingredientId: null,
          canonicalName: null,
          position: 3,
          displayName: 'Hành bo-rô (tỏi tây)',
          normalizedName: 'hanh bo ro',
          amount: 1,
          unit: 'cây',
          optional: false,
          resolutionStatus: 'UNKNOWN',
        },
      ],
    },
  },
  {
    id: 'rec-002',
    type: 'RECIPE',
    slug: 'canh-chua-nam-dau-bap-mien-tay',
    status: 'PUBLISHED',
    version: 1,
    publishedAt: '2026-09-11T09:45:00Z',
    createdAt: '2026-09-11T09:15:00Z',
    updatedAt: '2026-09-11T09:45:00Z',
    author: {
      id: 'usr-contributor-2',
      displayName: 'Tuệ Minh Vegan',
      avatarUrl:
        'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    },
    revision: {
      id: 'rev-002',
      version: 1,
      status: 'PUBLISHED',
      title: 'Canh chua nấm đậu bắp miền Tây',
      excerpt: 'Canh chua thanh mát vị me, nấm rơm giòn ngọt chuẩn vị miền Tây.',
      body: '## Bước 1\nĐun sôi 1 lít nước, cho me vắt vào dằm lấy nước chua rồi vớt bã.\n\n## Bước 2\nCho đậu bắp, cà chua, thơm vào nấu 5 phút, thêm nấm rơm nấu thêm 3 phút.\n\n## Bước 3\nNêm muối, đường, nước tương vừa ăn, rắc rau om và ớt trước khi tắt bếp.',
      tags: ['canh-chua', 'nam-rom', 'mien-tay'],
      createdAt: '2026-09-11T09:15:00Z',
    },
    categories: [
      { id: 'cat-recipe-2', name: 'Canh & Súp', slug: 'canh-sup', type: 'RECIPE_GROUP' },
    ],
    media: [
      {
        id: 'med-002',
        kind: 'COVER_IMAGE',
        provider: 'CLOUDINARY',
        secureUrl:
          'https://images.unsplash.com/photo-1547592180-85f173990554?w=800&auto=format&fit=crop&q=80',
        mimeType: 'image/jpeg',
        bytes: 110000,
      },
    ],
    recipe: {
      servings: 4,
      prepTimeMinutes: 20,
      cookTimeMinutes: 20,
      difficulty: 'EASY',
      nutrition: {
        calories: 145,
        proteinGrams: 7.2,
        carbsGrams: 22.4,
        fatGrams: 2.8,
        fiberGrams: 5.1,
        vitaminB12Mcg: 0.0,
      },
      mealPlannerEligible: true,
      allergenCodes: [],
      traditionWarnings: [],
      dietCompatibilities: [],
      ingredients: [
        {
          id: 'ri-005',
          ingredientId: 'ing-straw-mushroom',
          canonicalName: 'Nấm rơm',
          position: 0,
          displayName: 'Nấm rơm búp tươi',
          normalizedName: 'nam rom bup tuoi',
          amount: 200,
          unit: 'gram',
          optional: false,
          resolutionStatus: 'EXACT',
        },
        {
          id: 'ri-006',
          ingredientId: null,
          canonicalName: null,
          position: 1,
          displayName: 'Đậu bắp',
          normalizedName: 'dau bap',
          amount: 150,
          unit: 'gram',
          optional: false,
          resolutionStatus: 'UNKNOWN',
        },
        {
          id: 'ri-007',
          ingredientId: null,
          canonicalName: null,
          position: 2,
          displayName: 'Me vắt',
          normalizedName: 'me vat',
          amount: 50,
          unit: 'gram',
          optional: false,
          resolutionStatus: 'UNKNOWN',
        },
      ],
    },
  },
  {
    id: 'rec-003',
    type: 'RECIPE',
    slug: 'lau-nam-duong-sinh-ngot-nuoc',
    status: 'PUBLISHED',
    version: 1,
    publishedAt: '2026-09-12T10:00:00Z',
    createdAt: '2026-09-12T09:30:00Z',
    updatedAt: '2026-09-12T10:00:00Z',
    author: {
      id: 'usr-contributor-1',
      displayName: 'Bếp Chay An Nhiên',
      avatarUrl:
        'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    },
    revision: {
      id: 'rev-003',
      version: 1,
      status: 'PUBLISHED',
      title: 'Lẩu nấm dưỡng sinh ngọt nước',
      excerpt: 'Nước dùng ngọt tự nhiên từ mía lau, táo đỏ và 7 loại nấm tươi.',
      body: '## Bước 1\nNướng sơ mía lau, táo đỏ cho thơm rồi cho vào nồi nước dùng ninh 40 phút.\n\n## Bước 2\nSơ chế 7 loại nấm, rau ăn kèm, đậu hũ non cắt miếng vừa ăn.\n\n## Bước 3\nNêm nước dùng vừa ăn, nhúng nấm và rau khi thưởng thức cùng mì chay.',
      tags: ['lau-chay', 'nam', 'duong-sinh'],
      createdAt: '2026-09-12T09:30:00Z',
    },
    categories: [{ id: 'cat-recipe-3', name: 'Lẩu chay', slug: 'lau-chay', type: 'RECIPE_GROUP' }],
    media: [
      {
        id: 'med-003',
        kind: 'COVER_IMAGE',
        provider: 'CLOUDINARY',
        secureUrl:
          'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=800&auto=format&fit=crop&q=80',
        mimeType: 'image/jpeg',
        bytes: 130000,
      },
    ],
    recipe: {
      servings: 6,
      prepTimeMinutes: 30,
      cookTimeMinutes: 45,
      difficulty: 'MEDIUM',
      nutrition: {
        calories: 320,
        proteinGrams: 12.0,
        carbsGrams: 48.0,
        fatGrams: 6.5,
        fiberGrams: 8.0,
        vitaminB12Mcg: 0.0,
      },
      mealPlannerEligible: false,
      allergenCodes: [],
      traditionWarnings: [],
      dietCompatibilities: [],
      ingredients: [
        {
          id: 'ri-008',
          ingredientId: null,
          canonicalName: null,
          position: 0,
          displayName: 'Nấm thập cẩm các loại',
          normalizedName: 'nam thap cam',
          amount: 700,
          unit: 'gram',
          optional: false,
          resolutionStatus: 'UNKNOWN',
        },
        {
          id: 'ri-009',
          ingredientId: null,
          canonicalName: null,
          position: 1,
          displayName: 'Mía lau',
          normalizedName: 'mia lau',
          amount: 2,
          unit: 'khúc',
          optional: false,
          resolutionStatus: 'UNKNOWN',
        },
        {
          id: 'ri-010',
          ingredientId: null,
          canonicalName: null,
          position: 2,
          displayName: 'Táo đỏ',
          normalizedName: 'tao do',
          amount: 10,
          unit: 'quả',
          optional: false,
          resolutionStatus: 'UNKNOWN',
        },
      ],
    },
  },
];
