#!/usr/bin/env node
/*
 * sync-swagger.mjs — Chẻ 1 file OpenAPI/Swagger dài thành catalog gọn cho agent.
 *
 * Vấn đề: swagger.json của BE thường vài nghìn–vài chục nghìn dòng. Mỗi lần cần
 * 1 API mà bắt agent đọc cả file = tốn token, chậm, dễ hallucinate.
 *
 * Cách dùng:
 *   node scripts/sync-swagger.mjs [source]
 *   - source: đường dẫn tới swagger JSON hoặc URL http(s)://...
 *   - Mặc định: docs/swagger.json (file local, đã gitignore) hoặc env SWAGGER_URL.
 *
 *   Ví dụ:
 *     node scripts/sync-swagger.mjs docs/swagger.json
 *     SWAGGER_URL=http://localhost:8080/api-docs.json npm run sync:swagger
 *
 * Output (được commit, agent đọc các file này thay vì swagger gốc):
 *   docs/api-catalog.json   — machine-readable, gọn (method/path/schema rút gọn)
 *   docs/API-CATALOG.md     — index 1 trang: tag -> endpoints (đọc đầu tiên)
 *   docs/api/<tag>.md       — chi tiết từng nhóm (chỉ mở file của tag cần)
 *
 * Quy ước agent: đọc API-CATALOG.md -> mở 1 file docs/api/<tag>.md -> code.
 * CẤM đọc swagger gốc trong lúc code.
 */
import { mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const DOCS = join(ROOT, 'docs');
const API_DIR = join(DOCS, 'api');
const DEFAULT_SOURCE = join(DOCS, 'swagger.json');

const args = process.argv.slice(2).filter((a) => !a.startsWith('--'));
const source = args[0] || process.env.SWAGGER_URL || DEFAULT_SOURCE;
const isUrl = /^https?:\/\//i.test(source);
const GEN_HEAD = '<!-- GENERATED by scripts/sync-swagger.mjs — không sửa tay, chạy lại lệnh để regenerate -->';

async function loadSpec() {
  if (isUrl) {
    const res = await fetch(source);
    if (!res.ok) throw new Error(`fetch ${source}: ${res.status} ${res.statusText}`);
    return await res.json();
  }
  if (/\.ya?ml$/i.test(source)) {
    console.error(
      '✖ Script chỉ hỗ trợ swagger JSON.\n' +
        '  Từ YAML: mở BE /api-docs rồi "Save as JSON", hoặc export JSON từ Swagger Editor.'
    );
    process.exit(1);
  }
  try {
    return JSON.parse(readFileSync(source, 'utf8'));
  } catch {
    console.error(
      `✖ Không đọc được ${source}.\n` +
        '  - Cách 1: lưu file swagger JSON của BE vào docs/swagger.json\n' +
        '  - Cách 2: SWAGGER_URL=http://localhost:8080/api-docs.json npm run sync:swagger'
    );
    process.exit(1);
  }
}

const refName = (ref) => String(ref).split('/').pop();
const slug = (s) =>
  String(s || 'misc')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '') || 'misc';
const esc = (s) => String(s ?? '').replace(/\|/g, '\\|').replace(/\n+/g, ' ').slice(0, 120);

/** Lấy node local theo JSON-pointer nội bộ (#/components/schemas/X, #/parameters/X...). */
function makeGetter(spec) {
  return (pointer) => {
    if (!pointer?.startsWith('#/')) return undefined;
    return pointer
      .slice(2)
      .split('/')
      .reduce((acc, k) => acc?.[decodeURIComponent(k)], spec);
  };
}

/** Rút gọn schema: giữ type/format/enum/required/properties/items/allOf..., bỏ description/example. */
function compact(node, depth = 0) {
  if (node === null || node === undefined) return node;
  if (Array.isArray(node)) return node.map((x) => compact(x, depth));
  if (typeof node !== 'object') return node;
  if (node.$ref) return { $ref: refName(node.$ref) };
  if (depth > 2) return { type: node.type ?? 'object', _truncated: true };
  const out = {};
  for (const k of ['type', 'format', 'enum', 'nullable', 'required']) {
    if (node[k] !== undefined) out[k] = node[k];
  }
  if (node.properties) {
    out.properties = {};
    for (const [pk, pv] of Object.entries(node.properties)) out.properties[pk] = compact(pv, depth + 1);
  }
  if (node.items) out.items = compact(node.items, depth + 1);
  for (const k of ['allOf', 'oneOf', 'anyOf']) {
    if (node[k]) out[k] = node[k].map((x) => compact(x, depth + 1));
  }
  if (typeof node.additionalProperties === 'boolean') {
    out.additionalProperties = node.additionalProperties;
  }
  return out;
}

function schemaLabel(s) {
  if (!s || typeof s !== 'object') return '—';
  if (s.$ref) return refName(s.$ref);
  if (s.type === 'array') return `array<${schemaLabel(s.items)}>`;
  return s.type ?? 'object';
}

/** Thu thập tên schema ($ref) xuất hiện trong 1 object compact. */
function collectRefs(node, into) {
  if (!node || typeof node !== 'object') return;
  if (typeof node.$ref === 'string') {
    into.add(node.$ref);
    return;
  }
  for (const v of Object.values(node)) {
    if (v && typeof v === 'object') collectRefs(v, into);
  }
}

const METHOD_ORDER = ['get', 'post', 'put', 'patch', 'delete'];

async function main() {
  const spec = await loadSpec();
  const isV2 = !String(spec.openapi || '').startsWith('3');
  const getRef = makeGetter(spec);
  const schemas = spec.components?.schemas ?? spec.definitions ?? {};
  const paths = spec.paths ?? {};

  if (!Object.keys(paths).length) {
    console.error('✖ Spec không có paths nào. Kiểm tra lại file/URL swagger.');
    process.exit(1);
  }

  /** @type {Array} */
  const ops = [];
  for (const [path, pathItem] of Object.entries(paths)) {
    if (!pathItem || typeof pathItem !== 'object') continue;
    const sharedParams = pathItem.parameters ?? [];
    for (const method of METHOD_ORDER) {
      const op = pathItem[method];
      if (!op || typeof op !== 'object') continue;

      // Params (query/path) — resolve $ref #/parameters/*
      const params = [];
      for (const p of [...sharedParams, ...(op.parameters ?? [])]) {
        const prm = p?.$ref ? getRef(p.$ref) : p;
        if (!prm || prm.in === 'body' || prm.in === 'header' || prm.in === 'cookie') continue;
        if (prm.in !== 'query' && prm.in !== 'path') continue;
        params.push({
          in: prm.in,
          name: prm.name,
          required: !!prm.required,
          type: prm.schema ? schemaLabel(prm.schema) : (prm.type ?? 'string'),
        });
      }

      // Request body
      let request = null;
      if (isV2) {
        const bodyPrm = (op.parameters ?? [])
          .map((p) => (p?.$ref ? getRef(p.$ref) : p))
          .find((p) => p?.in === 'body' && p?.schema);
        if (bodyPrm) request = { schema: compact(bodyPrm.schema), required: !!bodyPrm.required };
      } else {
        const content = op.requestBody?.content ?? {};
        const json = content['application/json'] ?? Object.values(content)[0];
        if (json?.schema) {
          request = { schema: compact(json.schema), required: !!op.requestBody.required };
        }
      }

      // Responses
      const responses = {};
      for (const [code, r] of Object.entries(op.responses ?? {})) {
        const rr = r?.$ref ? getRef(r.$ref) : r;
        const schema = isV2
          ? rr?.schema
          : (rr?.content?.['application/json']?.schema ?? Object.values(rr?.content ?? {})[0]?.schema);
        responses[code] = schema ? schemaLabel(schema) : esc(rr?.description);
      }

      const firstSeg = (path.split('/').filter(Boolean)[0] || 'misc').toLowerCase();
      const tag = op.tags?.[0] || firstSeg;
      ops.push({
        method: method.toUpperCase(),
        path,
        group: tag,
        summary: op.summary || op.operationId || '',
        operationId: op.operationId || '',
        params,
        request,
        responses,
      });
    }
  }

  // Gom nhóm
  const groups = new Map();
  for (const op of ops) {
    if (!groups.has(op.group)) groups.set(op.group, []);
    groups.get(op.group).push(op);
  }

  // Schema compact toàn cục (chỉ những schema được tham chiếu + schema gốc rỗng thì bỏ qua)
  const usedRefs = new Set();
  for (const op of ops) {
    collectRefs(op.request?.schema, usedRefs);
  }
  const compactSchemas = {};
  for (const [name, s] of Object.entries(schemas)) {
    compactSchemas[name] = compact(s);
  }

  const generatedAt = new Date().toISOString();
  mkdirSync(API_DIR, { recursive: true });

  // 1) api-catalog.json
  const displaySource = isUrl ? source : relative(ROOT, source);
  const catalog = {
    $generated: 'scripts/sync-swagger.mjs — không sửa tay',
    source: displaySource,
    generatedAt,
    stats: { operations: ops.length, groups: groups.size, schemas: Object.keys(schemas).length },
    operations: ops,
  };
  writeFileSync(join(DOCS, 'api-catalog.json'), JSON.stringify(catalog, null, 2));

  // 2) API-CATALOG.md — index 1 trang
  let md = `${GEN_HEAD}\n# API Catalog\n\n`;
  md += `> Source: \`${displaySource}\` | Generated: ${generatedAt}\n`;
  md += `> ${ops.length} endpoints · ${groups.size} nhóm · ${Object.keys(schemas).length} schemas\n`;
  md += `> Quy tắc agent: đọc bảng dưới tìm tag/path → chỉ mở \`docs/api/<tag>.md\` tương ứng. Cấm đọc swagger gốc.\n\n`;
  const sortedGroups = [...groups.entries()].sort((a, b) => a[0].localeCompare(b[0]));
  for (const [tag, list] of sortedGroups) {
    md += `## ${tag} (${list.length}) → \`docs/api/${slug(tag)}.md\`\n\n`;
    md += `| Method | Path | Summary | Request | Responses |\n|---|---|---|---|---|\n`;
    for (const op of list) {
      const req = op.request ? schemaLabel(op.request.schema) : '—';
      const res = Object.entries(op.responses)
        .map(([c, s]) => `${c}:${s}`)
        .join(', ');
      md += `| ${op.method} | \`${op.path}\` | ${esc(op.summary)} | ${esc(req)} | ${esc(res)} |\n`;
    }
    md += `\n`;
  }
  writeFileSync(join(DOCS, 'API-CATALOG.md'), md);

  // 3) docs/api/<tag>.md — chi tiết từng nhóm (xóa file tag cũ không còn)
  const fresh = new Set();
  for (const [tag, list] of sortedGroups) {
    const file = `${slug(tag)}.md`;
    fresh.add(file);
    let g = `${GEN_HEAD}\n# ${tag}\n\n`;
    for (const op of list) {
      g += `## ${op.method} \`${op.path}\`\n`;
      if (op.summary) g += `${esc(op.summary, 200)}\n`;
      if (op.operationId) g += `- operationId: \`${op.operationId}\`\n`;
      g += `- Params: `;
      g += op.params.length
        ? op.params.map((p) => `\`${p.in}:${p.name}${p.required ? '*' : ''} (${p.type})\``).join(', ')
        : '—';
      g += `\n- Request: ${op.request ? `\`${schemaLabel(op.request.schema)}\`${op.request.required ? ' (required)' : ''}` : '—'}\n`;
      g += `- Responses: ${Object.entries(op.responses).map(([c, s]) => `\`${c}\` → ${s}`).join(', ') || '—'}\n`;
      if (op.request && !op.request.schema.$ref) {
        g += `\n\`\`\`json\n${JSON.stringify(op.request.schema).slice(0, 2000)}\n\`\`\`\n`;
      }
      g += `\n`;
    }
    // Schemas nhóm này dùng tới
    const refs = new Set();
    for (const op of list) collectRefs(op.request?.schema, refs);
    for (const op of list) {
      for (const r of Object.values(op.responses)) {
        if (schemas[r]) refs.add(r);
      }
    }
    if (refs.size) {
      g += `---\n### Schemas dùng trong nhóm\n\n`;
      for (const r of [...refs].sort()) {
        if (!compactSchemas[r]) continue;
        let dump = JSON.stringify(compactSchemas[r], null, 2);
        if (dump.length > 3000) dump = dump.slice(0, 3000) + '\n  …(truncated — xem api-catalog.json)';
        g += `#### ${r}\n\`\`\`json\n${dump}\n\`\`\`\n\n`;
      }
    }
    writeFileSync(join(API_DIR, file), g);
  }
  for (const f of readdirSync(API_DIR).filter((f) => f.endsWith('.md'))) {
    if (!fresh.has(f)) rmSync(join(API_DIR, f));
  }

  console.log(
    `✔ Done: ${ops.length} endpoints, ${groups.size} nhóm, ${Object.keys(schemas).length} schemas → docs/API-CATALOG.md + docs/api/*.md`
  );
}

main().catch((e) => {
  console.error('✖ sync-swagger thất bại:', e.message);
  process.exit(1);
});
